name: Deploy Containers to Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # set your GCP project & default Cloud Run region
    env:
      CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      CLOUDSDK_RUN_REGION: us-west1
      CLOUDSQL_INSTANCE: ${{ secrets.CLOUDSQL_INSTANCE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud & components
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Run backend
        run: |
          gcloud run deploy finly-backend-1m \
            --image=us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/capstone/backend:1m-sample \
            --platform=managed \
            --region=$CLOUDSDK_RUN_REGION \
            --allow-unauthenticated \
            --port=5001 \
            --timeout=900s \
            --memory=8Gi \
            --cpu=2 \
            --min-instances=1 \
            --add-cloudsql-instances=$CLOUDSQL_INSTANCE \
            --set-env-vars="PGHOST=/cloudsql/$CLOUDSQL_INSTANCE,PGPORT=${{ secrets.PGPORT }},PGDATABASE=${{ secrets.PGDATABASE }},PGUSER=${{ secrets.PGUSER }},PGPASSWORD=${{ secrets.PGPASSWORD }},PGTABLE=${{ secrets.PGTABLE }}"

      - name: Retrieve backend URL
        id: get-backend-url
        run: |
          echo "API_BASE_URL=$(gcloud run services describe finly-backend-1m \
            --platform=managed \
            --region=$CLOUDSDK_RUN_REGION \
            --format='value(status.url)')" >> $GITHUB_ENV

      - name: Deploy Cloud Run frontend
        run: |
          gcloud run deploy finly-frontend-1m \
            --image=us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/capstone/frontend:1m-sample \
            --platform=managed \
            --region=$CLOUDSDK_RUN_REGION \
            --allow-unauthenticated \
            --port=8501 \
            --min-instances=1 \
            --set-env-vars=API_BASE_URL=$API_BASE_URL
